title: Zhansaya Bortanova
#logo: https://instagram.fala2-1.fna.fbcdn.net/v/t51.2885-19/348854436_3611428885773101_5055632587166966955_n.jpg?stp=dst-jpg_s150x150&_nc_ht=instagram.fala2-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=AATMQv_rILgAX_5G1VZ&edm=ABmJApABAAAA&ccb=7-5&oh=00_AfBzJbiO4fArfNR3Dyuw9DaXPRkp7LQHH2DFr0aGcP9ezA&oe=659FC829&_nc_sid=b41fef
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
